version: 2
jobs:
  test:
    docker:
      - image: fabiogallotti/pytest
    steps:
      - checkout
      - run:
         name: Run tests
         command: |
           python -m pytest
workflows:
  version: 2
  push:
    jobs:
      - test

